// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 03 May 2020 18:58:25 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "leopard.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

